// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDEzs1Oc5iJ004PMnEGSEU3RXEwtnDMwo',
    appId: '1:1092875206780:web:c24b45a75f6d18a41b09f9',
    messagingSenderId: '1092875206780',
    projectId: 'comunicaoalternativa-53d9b',
    authDomain: 'comunicaoalternativa-53d9b.firebaseapp.com',
    storageBucket: 'comunicaoalternativa-53d9b.firebasestorage.app',
    measurementId: 'G-1FWG73FDWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5GKyAHtCkDpBIZWOqjnkETSw1dN1ZJS4',
    appId: '1:1092875206780:android:803ed91edff64f571b09f9',
    messagingSenderId: '1092875206780',
    projectId: 'comunicaoalternativa-53d9b',
    storageBucket: 'comunicaoalternativa-53d9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG94BCilqyoRvSTvBQ7ljr32Fs9WR9ddo',
    appId: '1:1092875206780:ios:551ed5b7cdea237a1b09f9',
    messagingSenderId: '1092875206780',
    projectId: 'comunicaoalternativa-53d9b',
    storageBucket: 'comunicaoalternativa-53d9b.firebasestorage.app',
    iosBundleId: 'com.example.comunicacaoAlternativaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG94BCilqyoRvSTvBQ7ljr32Fs9WR9ddo',
    appId: '1:1092875206780:ios:551ed5b7cdea237a1b09f9',
    messagingSenderId: '1092875206780',
    projectId: 'comunicaoalternativa-53d9b',
    storageBucket: 'comunicaoalternativa-53d9b.firebasestorage.app',
    iosBundleId: 'com.example.comunicacaoAlternativaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDEzs1Oc5iJ004PMnEGSEU3RXEwtnDMwo',
    appId: '1:1092875206780:web:6fcc24d43fd9b0701b09f9',
    messagingSenderId: '1092875206780',
    projectId: 'comunicaoalternativa-53d9b',
    authDomain: 'comunicaoalternativa-53d9b.firebaseapp.com',
    storageBucket: 'comunicaoalternativa-53d9b.firebasestorage.app',
    measurementId: 'G-1RMFDLG73E',
  );

}